# src/main/resources/application.yml
spring:
  mvc:
    throw-exception-if-no-handler-found: true
    web:
      resources:
        add-mappings: false
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update   # 개발용
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: debug

app:
  jwt:
    # 32바이트(256비트) 이상 Base64 시크릿 (임시값, 운영에서 교체)
    secret: "bXktdmVyeS1sb25nLXN1cGVyLXNlY3JldC1iYXNlNjQtMzJieXRlc2F0bGVhc3Q="
    expiration-minutes: 60
    issuer: "demo-auth"